sudo: required
services: 
  - docker
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - sh travis.sh
after_success:
  - echo Build success
after_failure:
  - echo Build failure
