sudo: required
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="8.11.4"
services: 
  - docker
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
  - npm install -g @angular/cli
script:
  - ./travis_script.sh
after_success:
  - echo Build success
after_failure:
  - echo Build failure
