sudo: required
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="8.11.4"
services: 
  - docker
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
script:
  - npm run travis-script
after_success:
  - echo Build success
after_failure:
  - echo Build failure
