sudo: required
services: 
  - docker
  - mysql
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('1234') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - bash travis.sh
after_success:
  - echo Build success
after_failure:
  - echo Build failure
