docker run -d --net host \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.Xauthority:$HOME/.Xauthority \
    -e HOME=$HOME \
    -e DISPLAY=$DISPLAY \
    -v $PWD/config:/app/config \
    -v $PWD:/app/videos \
    --device /dev/snd \
    --device /dev/video0 \
    cruizba/class-recorder

docker run -d -p 3306:3306 --name mysql_test -e MYSQL_DATABASE=class-recorder -e MYSQL_ROOT_PASSWORD=1234 mysql
