version: "2"
services:
  teacher-pc-server: 
    image: cruizba/class-recorder
    privileged: true
    network_mode: "host"
    environment:
      - HOME=$HOME
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR/pulse/native:$XDG_RUNTIME_DIR/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - $HOME/.Xauthority:$HOME/.Xauthority
      - $PWD/config:/app/config
      - $PWD/videos:/app/videos
    group_add:
      - $AUDIO_GROUP_CR
    devices:
      - /dev/snd
    depends_on:
      - mysql-server
    restart: unless-stopped
  mysql-server:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=class-recorder
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - $PWD/mysql:/var/lib/mysql


